Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageNameParameter
      InstanceType: !Ref InstanceTypeParameter
      SubnetId: !Ref SubnetIDParameter
      AvailabilityZone: !Ref AvailabilityZoneParameter
      SecurityGroupIds:
        - !Ref SecurityGroupIdParameter
      Tags:
        - Key: createdby
          Value: princea
        - Key: Name
          Value: !Ref InstanceNameParameter
Parameters:
  InstanceNameParameter:
    Type: String
    Description: Name of the ec2 instance
  ImageNameParameter: 
    Description: Select the image ami
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2
  InstanceTypeParameter: 
    Description: Select the instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
  SubnetIDParameter:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet IDs that is a List of Subnet Id
  SecurityGroupIdParameter:
    Type: AWS::EC2::SecurityGroup::Id
    Description: SG Id
  AvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Select the AZ
