Parameters: 
  # InstanceTypeParameter:
  #   Type: String
  #   Description: Select the instance type
  #   Default: t2.micro
  #   AllowedValues:
  #     - t2.micro
  #     - t2.small
  #     - t2.large
  #   ConstraintDescription: Select a valid instance type

  SecurityGroupIdParameter:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select Security group id

  EnvironmentName:
    Type: String
    Description: Environment name
    AllowedValues:
      - Dev
      - Prod
    ConstraintDescription: Select valid env values


Mappings:
  RegionMap: 
    us-east-1:
      ARM64K5: ami-08e4e35cccc6189f4
    eu-west-1:
      ARM64K5: ami-01efa4023f0f3a042
      ARM64K4: ami-096f7a9ab885b50f4
  
  Env2InstanceTypeMap:
    Dev:
      instanceType: t2.micro
    Prod:
      instanceType: t2.small



Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', ARM64K5]
      InstanceType: !FindInMap [Env2InstanceTypeMap, !Ref EnvironmentName, instanceType]
      SecurityGroupIds: 
        - !Ref SecurityGroupIdParameter
      Tags:
        - Key: createdby
          Value: princea
